// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef EVENT_ODB_HXX
#define EVENT_ODB_HXX

// Begin prologue.
//
#include <odb/qt/version.hxx>
#if ODB_QT_VERSION != 2050000 // 2.5.0
#  error ODB and C++ compilers see different libodb-qt interface versions
#endif
#include <odb/qt/basic/sqlite/qstring-traits.hxx>
#include <odb/qt/basic/sqlite/qbyte-array-traits.hxx>
#include <odb/qt/basic/sqlite/quuid-traits.hxx>
#include <odb/qt/containers/qhash-traits.hxx>
#include <odb/qt/containers/qlist-traits.hxx>
#include <odb/qt/containers/qlinked-list-traits.hxx>
#include <odb/qt/containers/qmap-traits.hxx>
#include <odb/qt/containers/qset-traits.hxx>
#include <odb/qt/containers/qvector-traits.hxx>
#include <odb/qt/date-time/sqlite/qdate-traits.hxx>
#include <odb/qt/date-time/sqlite/qtime-traits.hxx>
#include <odb/qt/date-time/sqlite/qdate-time-traits.hxx>
#include <QtCore/QSharedPointer>
#include <odb/qt/smart-ptr/pointer-traits.hxx>
#include <odb/qt/smart-ptr/wrapper-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "event.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Event
  //
  template <>
  struct class_traits< ::APSS::ODB::Event >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::APSS::ODB::Event >
  {
    public:
    typedef ::APSS::ODB::Event object_type;
    typedef ::QSharedPointer< ::APSS::ODB::Event > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::size_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // Event
  //
  template <typename A>
  struct query_columns< ::APSS::ODB::Event, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::size_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // label
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::QString,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    label_type_;

    static const label_type_ label;

    // subLabel
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::QString,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    subLabel_type_;

    static const subLabel_type_ subLabel;

    // camera
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::QString,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    camera_type_;

    static const camera_type_ camera;

    // startTime
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::QDateTime,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    startTime_type_;

    static const startTime_type_ startTime;

    // endTime
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::QDateTime,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    endTime_type_;

    static const endTime_type_ endTime;

    // trackerId
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    trackerId_type_;

    static const trackerId_type_ trackerId;

    // topScore
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    topScore_type_;

    static const topScore_type_ topScore;

    // score
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    score_type_;

    static const score_type_ score;

    // thumbnail
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::QString,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    thumbnail_type_;

    static const thumbnail_type_ thumbnail;

    // hasClip
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    hasClip_type_;

    static const hasClip_type_ hasClip;
  };

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::id_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::label_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  label (A::table_name, "\"label\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::subLabel_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  subLabel (A::table_name, "\"subLabel\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::camera_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  camera (A::table_name, "\"camera\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::startTime_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  startTime (A::table_name, "\"startTime\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::endTime_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  endTime (A::table_name, "\"endTime\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::trackerId_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  trackerId (A::table_name, "\"trackerId\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::topScore_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  topScore (A::table_name, "\"topScore\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::score_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  score (A::table_name, "\"score\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::thumbnail_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  thumbnail (A::table_name, "\"thumbnail\"", 0);

  template <typename A>
  const typename query_columns< ::APSS::ODB::Event, id_sqlite, A >::hasClip_type_
  query_columns< ::APSS::ODB::Event, id_sqlite, A >::
  hasClip (A::table_name, "\"hasClip\"", 0);

  template <typename A>
  struct pointer_query_columns< ::APSS::ODB::Event, id_sqlite, A >:
    query_columns< ::APSS::ODB::Event, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >:
    public access::object_traits< ::APSS::ODB::Event >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // label
      //
      details::buffer label_value;
      std::size_t label_size;
      bool label_null;

      // subLabel
      //
      details::buffer subLabel_value;
      std::size_t subLabel_size;
      bool subLabel_null;

      // camera
      //
      details::buffer camera_value;
      std::size_t camera_size;
      bool camera_null;

      // startTime
      //
      details::buffer startTime_value;
      std::size_t startTime_size;
      bool startTime_null;

      // endTime
      //
      details::buffer endTime_value;
      std::size_t endTime_size;
      bool endTime_null;

      // trackerId
      //
      long long trackerId_value;
      bool trackerId_null;

      // topScore
      //
      double topScore_value;
      bool topScore_null;

      // score
      //
      double score_value;
      bool score_null;

      // thumbnail
      //
      details::buffer thumbnail_value;
      std::size_t thumbnail_size;
      bool thumbnail_null;

      // hasClip
      //
      long long hasClip_value;
      bool hasClip_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 11UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::APSS::ODB::Event, id_common >:
    public access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >
  {
  };

  // Event
  //
}

#include "event-odb.ixx"

#include <odb/post.hxx>

#endif // EVENT_ODB_HXX
