// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "event-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // Event
  //

  struct access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::id_type
  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  id (const id_image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::size_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::id_type
  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::size_t,
          sqlite::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  grow (image_type& i,
        bool* t,
        const schema_version_migration& svm)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);
    ODB_POTENTIALLY_UNUSED (svm);

    bool grew (false);

    // id
    //
    t[0UL] = false;

    // label
    //
    if (t[1UL])
    {
      i.label_value.capacity (i.label_size);
      grew = true;
    }

    // subLabel
    //
    if (t[2UL])
    {
      i.subLabel_value.capacity (i.subLabel_size);
      grew = true;
    }

    // camera
    //
    if (t[3UL])
    {
      i.camera_value.capacity (i.camera_size);
      grew = true;
    }

    // startTime
    //
    if (t[4UL])
    {
      i.startTime_value.capacity (i.startTime_size);
      grew = true;
    }

    // endTime
    //
    if (t[5UL])
    {
      i.endTime_value.capacity (i.endTime_size);
      grew = true;
    }

    // trackerId
    //
    t[6UL] = false;

    // topScore
    //
    t[7UL] = false;

    // score
    //
    t[8UL] = false;

    // thumbnail
    //
    if (t[9UL])
    {
      i.thumbnail_value.capacity (i.thumbnail_size);
      grew = true;
    }

    // hasClip
    //
    t[10UL] = false;

    // licensePlateResults
    //
    if (svm >= schema_version_migration (2ULL, true))
    {
      if (t[11UL])
      {
        i.licensePlateResults_value.capacity (i.licensePlateResults_size);
        grew = true;
      }
    }

    return grew;
  }

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk,
        const schema_version_migration& svm)
  {
    ODB_POTENTIALLY_UNUSED (sk);
    ODB_POTENTIALLY_UNUSED (svm);

    using namespace sqlite;

    std::size_t n (0);

    // id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // label
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.label_value.data ();
    b[n].size = &i.label_size;
    b[n].capacity = i.label_value.capacity ();
    b[n].is_null = &i.label_null;
    n++;

    // subLabel
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.subLabel_value.data ();
    b[n].size = &i.subLabel_size;
    b[n].capacity = i.subLabel_value.capacity ();
    b[n].is_null = &i.subLabel_null;
    n++;

    // camera
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.camera_value.data ();
    b[n].size = &i.camera_size;
    b[n].capacity = i.camera_value.capacity ();
    b[n].is_null = &i.camera_null;
    n++;

    // startTime
    //
    b[n].type = sqlite::image_traits<
      ::QDateTime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.startTime_value.data ();
    b[n].size = &i.startTime_size;
    b[n].capacity = i.startTime_value.capacity ();
    b[n].is_null = &i.startTime_null;
    n++;

    // endTime
    //
    b[n].type = sqlite::image_traits<
      ::QDateTime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.endTime_value.data ();
    b[n].size = &i.endTime_size;
    b[n].capacity = i.endTime_value.capacity ();
    b[n].is_null = &i.endTime_null;
    n++;

    // trackerId
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.trackerId_value;
    b[n].is_null = &i.trackerId_null;
    n++;

    // topScore
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.topScore_value;
    b[n].is_null = &i.topScore_null;
    n++;

    // score
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i.score_value;
    b[n].is_null = &i.score_null;
    n++;

    // thumbnail
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.thumbnail_value.data ();
    b[n].size = &i.thumbnail_size;
    b[n].capacity = i.thumbnail_value.capacity ();
    b[n].is_null = &i.thumbnail_null;
    n++;

    // hasClip
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.hasClip_value;
    b[n].is_null = &i.hasClip_null;
    n++;

    // licensePlateResults
    //
    if (svm >= schema_version_migration (2ULL, true))
    {
      b[n].type = sqlite::image_traits<
        ::QString,
        sqlite::id_text>::bind_value;
      b[n].buffer = i.licensePlateResults_value.data ();
      b[n].size = &i.licensePlateResults_size;
      b[n].capacity = i.licensePlateResults_value.capacity ();
      b[n].is_null = &i.licensePlateResults_null;
    }

    n++;
  }

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk,
        const schema_version_migration& svm)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);
    ODB_POTENTIALLY_UNUSED (svm);

    using namespace sqlite;

    bool grew (false);

    // id
    //
    if (sk == statement_insert)
    {
      ::size_t const& v =
        o.id;

      bool is_null (false);
      sqlite::value_traits<
          ::size_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        v);
      i.id_null = is_null;
    }

    // label
    //
    {
      ::QString const& v =
        o.label;

      bool is_null (true);
      std::size_t cap (i.label_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.label_value,
        i.label_size,
        is_null,
        v);
      i.label_null = is_null;
      grew = grew || (cap != i.label_value.capacity ());
    }

    // subLabel
    //
    {
      ::QString const& v =
        o.subLabel;

      bool is_null (true);
      std::size_t cap (i.subLabel_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.subLabel_value,
        i.subLabel_size,
        is_null,
        v);
      i.subLabel_null = is_null;
      grew = grew || (cap != i.subLabel_value.capacity ());
    }

    // camera
    //
    {
      ::QString const& v =
        o.camera;

      bool is_null (true);
      std::size_t cap (i.camera_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.camera_value,
        i.camera_size,
        is_null,
        v);
      i.camera_null = is_null;
      grew = grew || (cap != i.camera_value.capacity ());
    }

    // startTime
    //
    {
      ::QDateTime const& v =
        o.startTime;

      bool is_null (true);
      std::size_t cap (i.startTime_value.capacity ());
      sqlite::value_traits<
          ::QDateTime,
          sqlite::id_text >::set_image (
        i.startTime_value,
        i.startTime_size,
        is_null,
        v);
      i.startTime_null = is_null;
      grew = grew || (cap != i.startTime_value.capacity ());
    }

    // endTime
    //
    {
      ::QDateTime const& v =
        o.endTime;

      bool is_null (true);
      std::size_t cap (i.endTime_value.capacity ());
      sqlite::value_traits<
          ::QDateTime,
          sqlite::id_text >::set_image (
        i.endTime_value,
        i.endTime_size,
        is_null,
        v);
      i.endTime_null = is_null;
      grew = grew || (cap != i.endTime_value.capacity ());
    }

    // trackerId
    //
    {
      int const& v =
        o.trackerId;

      bool is_null (false);
      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_image (
        i.trackerId_value,
        is_null,
        v);
      i.trackerId_null = is_null;
    }

    // topScore
    //
    {
      float const& v =
        o.topScore;

      bool is_null (true);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i.topScore_value,
        is_null,
        v);
      i.topScore_null = is_null;
    }

    // score
    //
    {
      float const& v =
        o.score;

      bool is_null (true);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i.score_value,
        is_null,
        v);
      i.score_null = is_null;
    }

    // thumbnail
    //
    {
      ::QString const& v =
        o.thumbnail;

      bool is_null (true);
      std::size_t cap (i.thumbnail_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.thumbnail_value,
        i.thumbnail_size,
        is_null,
        v);
      i.thumbnail_null = is_null;
      grew = grew || (cap != i.thumbnail_value.capacity ());
    }

    // hasClip
    //
    {
      bool const& v =
        o.hasClip;

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.hasClip_value,
        is_null,
        v);
      i.hasClip_null = is_null;
    }

    // licensePlateResults
    //
    if (svm >= schema_version_migration (2ULL, true))
    {
      {
        ::QString const& v =
          o.licensePlateResults;

        bool is_null (true);
        std::size_t cap (i.licensePlateResults_value.capacity ());
        sqlite::value_traits<
            ::QString,
            sqlite::id_text >::set_image (
          i.licensePlateResults_value,
          i.licensePlateResults_size,
          is_null,
          v);
        i.licensePlateResults_null = is_null;
        grew = grew || (cap != i.licensePlateResults_value.capacity ());
      }
    }

    return grew;
  }

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db,
        const schema_version_migration& svm)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (svm);

    // id
    //
    {
      ::size_t& v =
        o.id;

      sqlite::value_traits<
          ::size_t,
          sqlite::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // label
    //
    {
      ::QString& v =
        o.label;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.label_value,
        i.label_size,
        i.label_null);
    }

    // subLabel
    //
    {
      ::QString& v =
        o.subLabel;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.subLabel_value,
        i.subLabel_size,
        i.subLabel_null);
    }

    // camera
    //
    {
      ::QString& v =
        o.camera;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.camera_value,
        i.camera_size,
        i.camera_null);
    }

    // startTime
    //
    {
      ::QDateTime& v =
        o.startTime;

      sqlite::value_traits<
          ::QDateTime,
          sqlite::id_text >::set_value (
        v,
        i.startTime_value,
        i.startTime_size,
        i.startTime_null);
    }

    // endTime
    //
    {
      ::QDateTime& v =
        o.endTime;

      sqlite::value_traits<
          ::QDateTime,
          sqlite::id_text >::set_value (
        v,
        i.endTime_value,
        i.endTime_size,
        i.endTime_null);
    }

    // trackerId
    //
    {
      int& v =
        o.trackerId;

      sqlite::value_traits<
          int,
          sqlite::id_integer >::set_value (
        v,
        i.trackerId_value,
        i.trackerId_null);
    }

    // topScore
    //
    {
      float& v =
        o.topScore;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i.topScore_value,
        i.topScore_null);
    }

    // score
    //
    {
      float& v =
        o.score;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i.score_value,
        i.score_null);
    }

    // thumbnail
    //
    {
      ::QString& v =
        o.thumbnail;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.thumbnail_value,
        i.thumbnail_size,
        i.thumbnail_null);
    }

    // hasClip
    //
    {
      bool& v =
        o.hasClip;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.hasClip_value,
        i.hasClip_null);
    }

    // licensePlateResults
    //
    if (svm >= schema_version_migration (2ULL, true))
    {
      ::QString& v =
        o.licensePlateResults;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.licensePlateResults_value,
        i.licensePlateResults_size,
        i.licensePlateResults_null);
    }
  }

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          ::size_t,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Event\"\n"
  "(\"id\",\n"
  "\"label\",\n"
  "\"subLabel\",\n"
  "\"camera\",\n"
  "\"startTime\",\n"
  "\"endTime\",\n"
  "\"trackerId\",\n"
  "\"topScore\",\n"
  "\"score\",\n"
  "\"thumbnail\",\n"
  "\"hasClip\",\n"
  "\"licensePlateResults\")\n"
  "VALUES\n"
  "(?,\n?,\n?,\n?,\n?,\n?,\n?,\n?,\n?,\n?,\n?,\n?)";

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::find_statement[] =
  "SELECT\n"
  "\"Event\".\"id\",\n"
  "\"Event\".\"label\",\n"
  "\"Event\".\"subLabel\",\n"
  "\"Event\".\"camera\",\n"
  "\"Event\".\"startTime\",\n"
  "\"Event\".\"endTime\",\n"
  "\"Event\".\"trackerId\",\n"
  "\"Event\".\"topScore\",\n"
  "\"Event\".\"score\",\n"
  "\"Event\".\"thumbnail\",\n"
  "\"Event\".\"hasClip\",\n"
  "\"Event\".\"licensePlateResults\"\n"
  "FROM \"Event\"\n"
  "WHERE \"Event\".\"id\"=?";

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::update_statement[] =
  "UPDATE \"Event\"\n"
  "SET\n"
  "\"label\"=?,\n"
  "\"subLabel\"=?,\n"
  "\"camera\"=?,\n"
  "\"startTime\"=?,\n"
  "\"endTime\"=?,\n"
  "\"trackerId\"=?,\n"
  "\"topScore\"=?,\n"
  "\"score\"=?,\n"
  "\"thumbnail\"=?,\n"
  "\"hasClip\"=?,\n"
  "\"licensePlateResults\"=?\n"
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Event\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"Event\".\"id\",\n"
  "\"Event\".\"label\",\n"
  "\"Event\".\"subLabel\",\n"
  "\"Event\".\"camera\",\n"
  "\"Event\".\"startTime\",\n"
  "\"Event\".\"endTime\",\n"
  "\"Event\".\"trackerId\",\n"
  "\"Event\".\"topScore\",\n"
  "\"Event\".\"score\",\n"
  "\"Event\".\"thumbnail\",\n"
  "\"Event\".\"hasClip\",\n"
  "\"Event\".\"licensePlateResults\"\n"
  "FROM \"Event\"";

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Event\"";

  const char access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::table_name[] =
  "\"Event\"";

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  persist (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    const schema_version_migration& svm (sts.version_migration ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert, svm))
      im.version++;

    im.id_null = true;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert, svm);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const schema_version_migration& svm (sts.version_migration ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update, svm))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update, svm);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (!st.empty () && st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::pointer_type
  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    const schema_version_migration& svm (sts.version_migration ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id, svm))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db, svm);
      load_ (sts, obj, false, svm);
      sts.load_delayed (&svm);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    const schema_version_migration& svm (sts.version_migration ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id, svm))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db, svm);
    load_ (sts, obj, false, svm);
    sts.load_delayed (&svm);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    const schema_version_migration& svm (sts.version_migration ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id, svm))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db, svm);
    load_ (sts, obj, true, svm);
    sts.load_delayed (&svm);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id,
         const schema_version_migration& svm)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select, svm);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated (), svm))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select, svm);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::object_type >
  access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  query (database& db, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());
    const schema_version_migration& svm (sts.version_migration ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select, svm);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, &svm));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::APSS::ODB::Event, id_sqlite >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
