#ifndef _APSS_ORM_EXPORT_H_
#define _APSS_ORM_EXPORT_H_

#ifdef _MSC_VER
#pragma once
#endif

#ifdef _BUILDING_APSS_ORM
#define APSS_ORM_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_APSS_ORM
#define APSS_ORM_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_APSS_ORM

#ifdef _BUILDING_APSS_ORM
#define QX_REGISTER_HPP_APSS_ORM QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_APSS_ORM QX_REGISTER_CPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_APSS_ORM QX_REGISTER_COMPLEX_CLASS_NAME_HPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_APSS_ORM QX_REGISTER_COMPLEX_CLASS_NAME_CPP_EXPORT_DLL
#else // _BUILDING_APSS_ORM
#define QX_REGISTER_HPP_APSS_ORM QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_APSS_ORM QX_REGISTER_CPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_APSS_ORM QX_REGISTER_COMPLEX_CLASS_NAME_HPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_APSS_ORM QX_REGISTER_COMPLEX_CLASS_NAME_CPP_IMPORT_DLL
#endif // _BUILDING_APSS_ORM

#ifndef QX_DLL_EXPORT_APSS_ORM_SINGLETON_HPP
#ifdef _BUILDING_APSS_ORM
#define QX_DLL_EXPORT_APSS_ORM_SINGLETON_HPP(x) /* Nothing */
#else // _BUILDING_APSS_ORM
#define QX_DLL_EXPORT_APSS_ORM_SINGLETON_HPP(x) QX_DLL_EXPORT_TEMPLATE_HPP(class, qx::QxSingleton< x >)
#endif // _BUILDING_APSS_ORM
#endif // QX_DLL_EXPORT_APSS_ORM_SINGLETON_HPP

#ifndef QX_DLL_EXPORT_APSS_ORM_SINGLETON_CPP
#ifdef _BUILDING_APSS_ORM
#define QX_DLL_EXPORT_APSS_ORM_SINGLETON_CPP(x) QX_DLL_EXPORT_TEMPLATE_CPP(class, qx::QxSingleton< x >)
#else // _BUILDING_APSS_ORM
#define QX_DLL_EXPORT_APSS_ORM_SINGLETON_CPP(x) /* Nothing */
#endif // _BUILDING_APSS_ORM
#endif // QX_DLL_EXPORT_APSS_ORM_SINGLETON_CPP

#endif // _APSS_ORM_EXPORT_H_
