// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "exports-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // Exports
  //

  struct access::object_traits_impl< ::Exports, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::Exports, id_sqlite >::id_type
  access::object_traits_impl< ::Exports, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        id,
        i.m_id_value,
        i.m_id_size,
        i.m_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Exports, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_id
    //
    if (t[0UL])
    {
      i.m_id_value.capacity (i.m_id_size);
      grew = true;
    }

    // m_camera
    //
    if (t[1UL])
    {
      i.m_camera_value.capacity (i.m_camera_size);
      grew = true;
    }

    // m_name
    //
    if (t[2UL])
    {
      i.m_name_value.capacity (i.m_name_size);
      grew = true;
    }

    // m_date
    //
    if (t[3UL])
    {
      i.m_date_value.capacity (i.m_date_size);
      grew = true;
    }

    // m_videoPath
    //
    if (t[4UL])
    {
      i.m_videoPath_value.capacity (i.m_videoPath_size);
      grew = true;
    }

    // m_thumbPath
    //
    if (t[5UL])
    {
      i.m_thumbPath_value.capacity (i.m_thumbPath_size);
      grew = true;
    }

    // m_inProgress
    //
    t[6UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::Exports, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // m_id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::image_traits<
        ::QString,
        sqlite::id_text>::bind_value;
      b[n].buffer = i.m_id_value.data ();
      b[n].size = &i.m_id_size;
      b[n].capacity = i.m_id_value.capacity ();
      b[n].is_null = &i.m_id_null;
      n++;
    }

    // m_camera
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_camera_value.data ();
    b[n].size = &i.m_camera_size;
    b[n].capacity = i.m_camera_value.capacity ();
    b[n].is_null = &i.m_camera_null;
    n++;

    // m_name
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_name_value.data ();
    b[n].size = &i.m_name_size;
    b[n].capacity = i.m_name_value.capacity ();
    b[n].is_null = &i.m_name_null;
    n++;

    // m_date
    //
    b[n].type = sqlite::image_traits<
      ::QDateTime,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_date_value.data ();
    b[n].size = &i.m_date_size;
    b[n].capacity = i.m_date_value.capacity ();
    b[n].is_null = &i.m_date_null;
    n++;

    // m_videoPath
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_videoPath_value.data ();
    b[n].size = &i.m_videoPath_size;
    b[n].capacity = i.m_videoPath_value.capacity ();
    b[n].is_null = &i.m_videoPath_null;
    n++;

    // m_thumbPath
    //
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.m_thumbPath_value.data ();
    b[n].size = &i.m_thumbPath_size;
    b[n].capacity = i.m_thumbPath_value.capacity ();
    b[n].is_null = &i.m_thumbPath_null;
    n++;

    // m_inProgress
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.m_inProgress_value;
    b[n].is_null = &i.m_inProgress_null;
    n++;
  }

  void access::object_traits_impl< ::Exports, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::image_traits<
      ::QString,
      sqlite::id_text>::bind_value;
    b[n].buffer = i.id_value.data ();
    b[n].size = &i.id_size;
    b[n].capacity = i.id_value.capacity ();
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Exports, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // m_id
    //
    if (sk == statement_insert)
    {
      ::QString const& v =
        o.id ();

      bool is_null (false);
      std::size_t cap (i.m_id_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.m_id_value,
        i.m_id_size,
        is_null,
        v);
      i.m_id_null = is_null;
      grew = grew || (cap != i.m_id_value.capacity ());
    }

    // m_camera
    //
    {
      ::QString const& v =
        o.camera ();

      bool is_null (true);
      std::size_t cap (i.m_camera_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.m_camera_value,
        i.m_camera_size,
        is_null,
        v);
      i.m_camera_null = is_null;
      grew = grew || (cap != i.m_camera_value.capacity ());
    }

    // m_name
    //
    {
      ::QString const& v =
        o.name ();

      bool is_null (true);
      std::size_t cap (i.m_name_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.m_name_value,
        i.m_name_size,
        is_null,
        v);
      i.m_name_null = is_null;
      grew = grew || (cap != i.m_name_value.capacity ());
    }

    // m_date
    //
    {
      ::QDateTime const& v =
        o.date ();

      bool is_null (true);
      std::size_t cap (i.m_date_value.capacity ());
      sqlite::value_traits<
          ::QDateTime,
          sqlite::id_text >::set_image (
        i.m_date_value,
        i.m_date_size,
        is_null,
        v);
      i.m_date_null = is_null;
      grew = grew || (cap != i.m_date_value.capacity ());
    }

    // m_videoPath
    //
    {
      ::QString const& v =
        o.videoPath ();

      bool is_null (true);
      std::size_t cap (i.m_videoPath_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.m_videoPath_value,
        i.m_videoPath_size,
        is_null,
        v);
      i.m_videoPath_null = is_null;
      grew = grew || (cap != i.m_videoPath_value.capacity ());
    }

    // m_thumbPath
    //
    {
      ::QString const& v =
        o.thumbPath ();

      bool is_null (true);
      std::size_t cap (i.m_thumbPath_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.m_thumbPath_value,
        i.m_thumbPath_size,
        is_null,
        v);
      i.m_thumbPath_null = is_null;
      grew = grew || (cap != i.m_thumbPath_value.capacity ());
    }

    // m_inProgress
    //
    {
      bool const& v =
        o.inProgress ();

      bool is_null (false);
      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_image (
        i.m_inProgress_value,
        is_null,
        v);
      i.m_inProgress_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::Exports, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_id
    //
    {
      ::QString v;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.m_id_value,
        i.m_id_size,
        i.m_id_null);

      o.setId (v);
    }

    // m_camera
    //
    {
      ::QString v;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.m_camera_value,
        i.m_camera_size,
        i.m_camera_null);

      o.setCamera (v);
    }

    // m_name
    //
    {
      ::QString v;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.m_name_value,
        i.m_name_size,
        i.m_name_null);

      o.setName (v);
    }

    // m_date
    //
    {
      ::QDateTime v;

      sqlite::value_traits<
          ::QDateTime,
          sqlite::id_text >::set_value (
        v,
        i.m_date_value,
        i.m_date_size,
        i.m_date_null);

      o.setDate (v);
    }

    // m_videoPath
    //
    {
      ::QString v;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.m_videoPath_value,
        i.m_videoPath_size,
        i.m_videoPath_null);

      o.setVideoPath (v);
    }

    // m_thumbPath
    //
    {
      ::QString v;

      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_value (
        v,
        i.m_thumbPath_value,
        i.m_thumbPath_size,
        i.m_thumbPath_null);

      o.setThumbPath (v);
    }

    // m_inProgress
    //
    {
      bool v;

      sqlite::value_traits<
          bool,
          sqlite::id_integer >::set_value (
        v,
        i.m_inProgress_value,
        i.m_inProgress_null);

      o.setInProgress (v);
    }
  }

  void access::object_traits_impl< ::Exports, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t cap (i.id_value.capacity ());
      sqlite::value_traits<
          ::QString,
          sqlite::id_text >::set_image (
        i.id_value,
        i.id_size,
        is_null,
        id);
      i.id_null = is_null;
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::Exports, id_sqlite >::persist_statement[] =
  "INSERT INTO \"Exports\" "
  "(\"id\", "
  "\"camera\", "
  "\"name\", "
  "\"date\", "
  "\"videoPath\", "
  "\"thumbPath\", "
  "\"inProgress\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::Exports, id_sqlite >::find_statement[] =
  "SELECT "
  "\"Exports\".\"id\", "
  "\"Exports\".\"camera\", "
  "\"Exports\".\"name\", "
  "\"Exports\".\"date\", "
  "\"Exports\".\"videoPath\", "
  "\"Exports\".\"thumbPath\", "
  "\"Exports\".\"inProgress\" "
  "FROM \"Exports\" "
  "WHERE \"Exports\".\"id\"=?";

  const char access::object_traits_impl< ::Exports, id_sqlite >::update_statement[] =
  "UPDATE \"Exports\" "
  "SET "
  "\"camera\"=?, "
  "\"name\"=?, "
  "\"date\"=?, "
  "\"videoPath\"=?, "
  "\"thumbPath\"=?, "
  "\"inProgress\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::Exports, id_sqlite >::erase_statement[] =
  "DELETE FROM \"Exports\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::Exports, id_sqlite >::query_statement[] =
  "SELECT "
  "\"Exports\".\"id\", "
  "\"Exports\".\"camera\", "
  "\"Exports\".\"name\", "
  "\"Exports\".\"date\", "
  "\"Exports\".\"videoPath\", "
  "\"Exports\".\"thumbPath\", "
  "\"Exports\".\"inProgress\" "
  "FROM \"Exports\"";

  const char access::object_traits_impl< ::Exports, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"Exports\"";

  const char access::object_traits_impl< ::Exports, id_sqlite >::table_name[] =
  "\"Exports\"";

  void access::object_traits_impl< ::Exports, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Exports, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Exports, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Exports, id_sqlite >::pointer_type
  access::object_traits_impl< ::Exports, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Exports, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Exports, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Exports, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Exports, id_sqlite >::object_type >
  access::object_traits_impl< ::Exports, id_sqlite >::
  query (database& db, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Exports, id_sqlite >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
